### ISSUE TITLE
Difference in Indonesia's Gini for 2019 between PIP and PovcalNet

### ISSUE THREAD

**Issue by danielmahler** [worldbank/pip#33] opened 2022-03-01 17:03 UTC
You might be aware of this but just checking: Indonesia's Gini is about 0.2 point different between PIP and PovcalNet for 2019 

![image](https://user-images.githubusercontent.com/53179756/156214377-a849d909-ac5a-49bd-a16e-e739c2de0409.png)

![image](https://user-images.githubusercontent.com/53179756/156213991-159e96a1-72e8-407b-8865-357d479e019e.png)

**Comment by randrescastaneda** [comment] 2022-10-19 01:05
Yes, you're right. I think it is due to population adjustment. I already asked the Poverty GP to confirm their numbers. 

## Povcalnet
![image](https://user-images.githubusercontent.com/35301997/196573269-f48cf342-e16e-4e20-98ba-d9f3d13b483d.png)

## PIP (Oct 2022)
![image](https://user-images.githubusercontent.com/35301997/196573307-b22f0630-fe34-47a0-9f65-3398510cbf7f.png)

**Comment by randrescastaneda** [comment] 2022-10-20 16:46
I just confirmed with Poverty GP, and they replicated the same numbers that we have in PIP, so I am closing this issue.

**Closed by randrescastaneda** 2022-10-20 16:46 UTC
